import type { ReactNode } from "react";
import { createContext, useContext, useMemo } from "react";
import { createEditorStore } from "./editorStore";
import type { EditorActions, EditorState, EditorStore } from "./types";

const noopActions: EditorActions = {
  onChangeProjectTitle: () => {},
  onDownloadAll: () => {},
  onDownloadPdf: () => {},
  onShareAll: () => {},
  onOpenShareCarousels: () => {},
  onSignOut: () => {},
  onChangeNewProjectTemplateTypeId: () => {},
  onClickNewProject: () => {},
  onOpenTemplateSettings: () => {},
  onCloseTemplateSettings: () => {},
  onOpenTemplateEditor: () => {},
  onRefreshTemplatesList: () => {},
  onOpenPromptModal: () => {},
  onClosePromptsModal: () => {},
  onChangeTemplateTypePrompt: () => {},
  onChangeTemplateTypeBestPractices: () => {},
  onChangeTemplateTypeEmphasisPrompt: () => {},
  onChangeTemplateTypeImageGenPrompt: () => {},
  onChangeCaptionRegenPrompt: () => {},
  onChangeHeadlineFontKey: () => {},
  onChangeBodyFontKey: () => {},
  onChangeBackgroundColor: () => {},
  onChangeTextColor: () => {},
  onChangeBackgroundEffectEnabled: () => {},
  onChangeBackgroundEffectType: () => {},
  onSelectTheme: () => {},
  onResetThemeDefaults: () => {},
  onToggleProjectsDropdown: () => {},
  onLoadProject: () => {},
  onRequestArchive: () => {},
  onCancelArchive: () => {},
  onConfirmArchive: () => {},
  onChangeTemplateTypeMappingSlide1: () => {},
  onChangeTemplateTypeMappingSlide2to5: () => {},
  onChangeTemplateTypeMappingSlide6: () => {},

  onChangeHeadlineFontSize: () => {},
  onClickHeadlineAlign: () => {},
  onChangeHeadlineRichText: () => {},
  onChangeBodyFontSize: () => {},
  onClickBodyAlign: () => {},
  onChangeBodyRichText: () => {},
  onClickRegenerateImagePrompt: () => {},
  onChangeAiImagePrompt: () => {},
  onClickGenerateAiImage: () => {},
  onClickGenerateCopy: () => {},
  onSetGenerateCopyUi: () => {},
  onClickRetry: () => {},
  onClickRealignText: () => {},
  onClickUndo: () => {},
  onClickToggleOverlays: () => {},
  onClickCopyCaption: () => {},
  onClickRegenerateCaption: () => {},
  onChangeCaption: () => {},
  onClickCopyOutreachMessage: () => {},
  onChangeOutreachMessage: () => {},
  onOpenBodyRegenModal: () => {},
  onCloseBodyRegenModal: () => {},
  fetchBodyRegenAttempts: async () => [],
  onRunBodyRegen: async () => ({ body: "", bodyStyleRanges: [] }),
  onRestoreBodyRegenAttempt: async () => {},
  onOpenBodyEmphasisModal: () => {},
  onCloseBodyEmphasisModal: () => {},
  fetchBodyEmphasisAttempts: async () => [],
  onRunBodyEmphasisRegen: async () => ({ bodyStyleRanges: [] }),
  onRestoreBodyEmphasisAttempt: async () => {},
  onOpenEmphasisAllModal: () => {},
  onCloseEmphasisAllModal: () => {},
  onRunEmphasisAllRegen: async () => {},
  onOpenBrandAlignmentModal: () => {},
  onCloseBrandAlignmentModal: () => {},
  onChangeBrandAlignmentPrompt: () => {},
  onClickRunBrandAlignmentCheck: () => {},
  setIsSuperadmin: () => {},
  onCloseShareCarousels: () => {},
  onRefreshShareCarousels: async () => {},
  onClickCopyShareCarouselsLink: async () => {},
  onToggleProjectReviewReady: async () => {},
  onToggleProjectReviewPosted: async () => {},
  onToggleProjectReviewApproved: async () => {},
  onToggleProjectReviewScheduled: async () => {},
  onChangeProjectReviewSource: async () => {},
  setShowDebugPreview: () => {},
  setActiveSlideImageBgRemoval: () => {},
  deleteImageForActiveSlide: () => {},
  onOpenImageLibraryModal: () => {},
  onCloseImageLibraryModal: () => {},
  onToggleImageLibraryBgRemovalAtInsert: () => {},
  onOpenIdeasModal: () => {},
  onCloseIdeasModal: () => {},
  onOpenCreateAccountModal: () => {},
  onCloseCreateAccountModal: () => {},
  onOpenDeleteAccountModal: () => {},
  onCloseDeleteAccountModal: () => {},
  onOpenOutreachModal: () => {},
  onCloseOutreachModal: () => {},
  onOpenPoppyPromptsLibrary: () => {},
  onClosePoppyPromptsLibrary: () => {},
  hydrateActivePoppyPrompt: () => {},
  setPoppyPromptsLibraryUi: () => {},
  fetchPoppyPromptsLibrary: async () => [],
  createPoppyPrompt: async () => ({ id: "", title: "", prompt: "", is_active: false, created_at: "", updated_at: "" }),
  updatePoppyPrompt: async () => ({ id: "", title: "", prompt: "", is_active: false, created_at: "", updated_at: "" }),
  duplicatePoppyPrompt: async () => ({ id: "", title: "", prompt: "", is_active: false, created_at: "", updated_at: "" }),
  setActivePoppyPrompt: async () => ({ id: "", title: "", prompt: "", is_active: true, created_at: "", updated_at: "" }),
  fetchIdeaSourcesAndIdeas: async () => [],
  fetchIdeasPromptOverride: async () => "",
  saveIdeasPromptOverride: async (next: string) => String(next || ""),
  fetchIdeasPromptAudience: async () => "",
  saveIdeasPromptAudience: async (next: string) => String(next || ""),
  runGenerateIdeas: async () => ({}),
  updateIdea: async () => ({}),
  deleteIdeaSource: async () => ({}),
  createCarouselFromIdea: async () => ({ projectId: "" }),
  fetchProjectJobStatus: async () => ({}),
  fetchIdeaCarouselRuns: async () => ({}),
  fetchRecentAssets: async () => [],
  onInsertRecentImage: () => {},

  // Logos (Phase 3C: read-only)
  fetchLogoTags: async () => [],
  searchLogoVariants: async () => [],
  searchLogoVariantsGlobal: async () => [],
  importLogoVariant: async () => ({ cached: true, assetUrl: "", storage: { bucket: "", path: "" } }),
  insertCachedLogoToActiveSlide: async () => {},
};

const defaultState: EditorState = {
  titleText: "The Fittest You - AI Carousel Generator",
  projectTitle: "Untitled Project",
  projectTitleDisabled: false,
  isMobile: false,
  isSuperadmin: false,
  topExporting: false,
  engineSaveStatus: "idle",
  promptSaveStatus: "idle",
  projectSaveStatus: "idle",
  slideSaveStatus: "idle",
  currentProjectId: null,
  activeSlideIndex: 0,
  templateTypeId: "regular",
  newProjectTemplateTypeId: "enhanced",
  switchingSlides: false,
  loading: false,
  templateTypePromptPreviewLine: "",
  templateTypeBestPracticesPreviewLine: "",
  templateTypeEmphasisPromptPreviewLine: "",
  templateTypeImageGenPromptPreviewLine: "",
  templateSettingsOpen: false,
  promptModalOpen: false,
  promptModalSection: "prompt",
  poppyPromptsLibraryOpen: false,
  imageLibraryModalOpen: false,
  imageLibraryBgRemovalEnabledAtInsert: false,
  ideasModalOpen: false,
  createAccountModalOpen: false,
  deleteAccountModalOpen: false,
  outreachModalOpen: false,
  brandAlignmentModalOpen: false,
  shareCarouselsModalOpen: false,
  bodyRegenModalOpen: false,
  bodyRegenTargetProjectId: null,
  bodyRegenTargetSlideIndex: null,
  bodyEmphasisModalOpen: false,
  bodyEmphasisTargetProjectId: null,
  bodyEmphasisTargetSlideIndex: null,
  emphasisAllModalOpen: false,

  poppyPromptsLibraryStatus: "idle",
  poppyPromptsLibraryError: null,
  poppyPromptsLibraryPrompts: [],
  poppyActivePromptId: null,
  poppyPromptSaveStatus: "idle",
  poppyPromptSaveError: null,

  reviewReady: false,
  reviewPosted: false,
  reviewApproved: false,
  reviewScheduled: false,
  reviewComment: "",
  reviewSource: "",

  shareCarouselsLinkPath: null,
  shareCarouselsLinkLoading: false,
  shareCarouselsLinkError: null,
  shareCarouselsProjectsLoading: false,
  shareCarouselsProjectsError: null,
  shareCarouselsProjects: [],
  shareCarouselsSavingIds: new Set<string>(),
  templateTypePrompt: "",
  templateTypeBestPractices: "",
  templateTypeEmphasisPrompt: "",
  templateTypeImageGenPrompt: "",
  captionRegenPrompt: "",
  captionRegenPromptSaveStatus: "idle",
  captionRegenPromptSaveError: null,
  brandAlignmentPrompt: "",
  brandAlignmentPromptSaveStatus: "idle",
  brandAlignmentPromptSaveError: null,
  brandAlignmentRunStatus: "idle",
  brandAlignmentRunError: null,
  brandAlignmentLatestResult: null,
  brandAlignmentRunsStatus: "idle",
  brandAlignmentRunsError: null,
  brandAlignmentRuns: [],
  templateTypeMappingSlide1: null,
  templateTypeMappingSlide2to5: null,
  templateTypeMappingSlide6: null,
  loadingTemplates: false,
  templates: [],
  fontOptions: [],
  headlineFontKey: "",
  bodyFontKey: "",
  projectBackgroundColor: "#ffffff",
  projectTextColor: "#000000",
  projectBackgroundEffectEnabled: false,
  projectBackgroundEffectType: "none",
  projectBackgroundEffectSettings: {},
  themeIdLastApplied: null,
  themeIsCustomized: false,
  themeDefaultsSnapshot: null,
  lastManualBackgroundColor: null,
  lastManualTextColor: null,
  projects: [],
  projectsLoading: false,
  projectsDropdownOpen: false,
  archiveProjectModalOpen: false,
  archiveProjectTarget: null,
  archiveProjectBusy: false,
  workspace: null,
  workspaceNav: null,
  workspaceRefs: null,
  workspaceUi: null,
  workspaceActions: null,
  bottomPanel: null,
  bottomPanelUi: null,
  actions: noopActions,
};

const EditorStoreContext = createContext<EditorStore | null>(null);

export function EditorStoreProvider({ children }: { children: ReactNode }) {
  const store = useMemo(() => createEditorStore(defaultState), []);
  return <EditorStoreContext.Provider value={store}>{children}</EditorStoreContext.Provider>;
}

export function useEditorStore(): EditorStore {
  const store = useContext(EditorStoreContext);
  if (!store) {
    throw new Error("useEditorStore must be used within EditorStoreProvider");
  }
  return store;
}

